apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdisallowrunasroot
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  crd:
    spec:
      names:
        kind: K8sDisallowRunAsRoot
      validation:
        openAPIV3Schema:
          type: object
          properties: {}
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8sdisallowrunasroot

      violation[{"msg": msg}] {
        input.review.object.spec.securityContext.runAsUser == 0
        msg := "pod-level securityContext.runAsUser must not be 0"
      }

      violation[{"msg": msg}] {
        container := input.review.object.spec.containers[_]
        container.securityContext.runAsUser == 0
        msg := sprintf("container <%s> securityContext.runAsUser must not be 0", [container.name])
      }

      violation[{"msg": msg}] {
        container := input.review.object.spec.initContainers[_]
        container.securityContext.runAsUser == 0
        msg := sprintf("initContainer <%s> securityContext.runAsUser must not be 0", [container.name])
      }