apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdeploymentreplicalimit
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  crd:
    spec:
      names:
        kind: K8sDeploymentReplicaLimit
      validation:
        openAPIV3Schema:
          type: object
          properties:
            maxReplicas:
              type: integer
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8sdeploymentreplicalimit

      violation[{"msg": msg}] {
        input.review.kind.kind == "Deployment"
        replicas := input.review.object.spec.replicas
        max := input.parameters.maxReplicas
        replicas > max
        msg := sprintf("deployment <%s> has replicas %v, which exceeds the allowed maximum %v", [input.review.object.metadata.name, replicas, max])
      }