apiVersion: v1
kind: Pod
metadata:
  name: signed-w10-api-test
  namespace: demo
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
    - name: signed-w10-api-test
      image: ghcr.io/ngonguyentruongan/w10-api@sha256:de3471737c341212588d8ddc616f85dc64164eb0240eacadb846e8b0c8266033
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
