apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisallowRunAsRoot
metadata:
  name: disallow-run-as-root
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    excludedNamespaces:
    - kube-system
    - argocd
    - gatekeeper-system