# ArgoCD App: Deploy payments application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-payments
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/ngoNguyenTruongAn/Xbrain-W10-temp.git
    path: apps/payments
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: payments
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
