# ArgoCD App: Deploy tenant payments (namespace + RBAC + quota + limitrange + netpol)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-payments
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/ngoNguyenTruongAn/Xbrain-W10-temp.git
    path: tenants/payments
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
